### ISSUE TITLE
Only allow HTTPS-enabled sites to be loaded

### ISSUE THREAD

**Issue by lobenichou** [slifty/internet_noise#12]
Currently, Internet Noise loads http and https. However, with `HTTPS Everywhere` enabled, it eventually stops working. For this reason --and also because it is more secure, I think we should only loads HTTPS-enabled sites.

**Comment by peterberbec** [comment]
Fixed
https://github.com/slifty/internet_noise/pull/11

**Comment by slifty** [comment]
One thought here -- if the purpose is to generate *noise* in a sense might we actually prefer the fake traffic to be as transparent as possible?

In other words, might we ironically want *no* HTTPS enabled sites to be loaded?

**Comment by Prinzhorn** [comment]
> In other words, might we ironically want no HTTPS enabled sites to be loaded?

I don't know much about the bill being passed or how isps work, but doesn't HTTPS actually prevent any tracking by your isp anyway? There's no data they could sell, other than the IP you connect to. They neither know the URL nor the content of it.

**Comment by peterberbec** [comment]
Seems this is [correct](http://stackoverflow.com/questions/499591/are-https-urls-encrypted)

So we DON'T want https :)

**Comment by slifty** [comment]
Indeed @Prinzhorn -- HTTPS means the ISP would be able to see the site / IP you visit but not what content or what specific page you loaded

**Comment by slifty** [comment]
@laurenbenichou given the above do you still think HTTPS-only is something you would like to see given the goals around noise (vs around enforcing good HTTPS habits, which HTTPS Everywhere accomplishes)?

It seems that it could be supported at the very least as an option.

**Comment by peterberbec** [comment]
It's a one-character change.

`inurl:https` vs
`-inurl:https`

**Comment by lobenichou** [comment]
Two things: 
- When HTTPS Everywhere is enabled, Noise eventually stops loading sites. 
- Noise seems to only loads sites. It doesn't interact with said site --or does it? In that case, what data would the ISP get aside from the IP of the site you've visited? Also currently reading [this](https://www.teamupturn.com/reports/2016/what-isps-can-see#even-with-https-isps-can-still-see-the-domains-that-their-subscribers-visit)

**Comment by peterberbec** [comment]
Best I can figure, the Google search query is encrypted, the dns lookups are not, and any request to the resulting site, if https, is encrypted. They won't get the search terms or the name of the page loaded, just the domain name lookup. 

From the page you referenced: `Encryption stops ISPs from simply reading content and URL information directly off the wire.`

Maybe a better noise generator would be to do dns lookups?

**Comment by lobenichou** [comment]
That's interesting. Yes, maybe a way to make more noise is to look past loading random URLs, but actually loading the data the ISP is looking at.

**Comment by slifty** [comment]
So just to note: non-encrypted (e.g. HTTP) traffic means that the ISP has access to the actual content of the page. That means they know that someone is reading articles about "home birth" or "private school" or "the flying spaghetti monster" (and know exactly what points were being made in those articles) and therefore track life trends and preferences in the same way an advertiser might.  Then they can resell that analysis.

I totally agree that noise at DNS level would be a response to the less invasive form of observation that ya'll are talking about, but there is more invasive tracking on the table here that ISPs are able to do.  Basically, we shouldn't ignore the HTTP threat which most non tech savvy users are going to be victim to.

Right now this iteration of a noise machine is able to create some noise in the HTTP space (and the HTTPS too, since each HTTPS request does generate DNS lookups, although less efficiently than a straight-up-DNS-noise tool might).

TO BE CLEAR: if we want to make this actually effective, we are going to need to focus on things that make it look more human; there are papers written about this which I should pull up.  The short story is that most experts think noise is NOT an effective way to fight surveillance.

The key question is whether or not random HTTP traffic poses a threat to the user.  I went in this assuming the answer is no -- as in, no harm -- since nothing about the user's true self is being communicated to the ISP (because each request is random).  The raised issue is important though, and if we think random HTTP traffic is harmful then we should probably convert it to HTTPS!

**Comment by lobenichou** [comment]
`The raised issue is important though, and if we think random HTTP traffic is harmful then we should probably convert it to HTTPS!` --> AGREED!

And you don't feel like it's harmful, then you should put a disclaimer about disabling HTTPS Everywhere for Noise to work.

**Comment by SebastianBoyd** [comment]
I think that HTTPS sites should be removed from the noise. Especially the google searches. Since the isp cant see the actual content of the searches they are pretty useless at generating noise.

**Comment by mattmcm** [comment]
Hi, new here. Hopefully this isn't a stupid suggestion...

Instead of disabling HTTPS Everywhere to use Noise, would it be possible to change Noise code to pre-test the URL (cert?) to avoid privacy errors (which I presume is what is breaking the app). Alternatively, and I don't know if this is possible, but could the target tab be checked to see if it currently displaying a privacy error, in which case, close the tab and open a new one.

Again, I don't know anything about the code at this stage so these might be stupid / invalid suggestions. 

Thanks again for putting this together though.
