### ISSUE TITLE
Why not using a single page instead a lot of tabs.

### ISSUE THREAD

**Issue by Dieg0x17** [slifty/internet_noise#18]
Could you use an iframe or more to make the requests.

**Comment by slifty** [comment]
Great thinking -- in fact, iframes were the first attempt.  They unfortunately don't work because of cross domain origin policies (you generally can't load a third party site into your own iframes because the domain names don't match)

As for using five tabs instead of one -- one tab doesn't sound very noisy now does it!

More seriously: there are some requests to make it possible to change parameters -- for instance, load only one page at a time, or load more than 5.  I expect this is something that will be added shortly, though unfortunately no matter how you slice it we will need to use a tab.
